callbacks:
  patience: 100
  tol: 0
task:
  task_name: StateEstimation
  noise_type: Gaussian
  measurements:
    power_inj:
      mask_ratio: 0.2
      outlier_ratio: 0.1
      std: 0.02
    power_flow:
      mask_ratio: 0.2
      outlier_ratio: 0.1
      std: 0.02
    vm:
      mask_ratio: 0.2
      outlier_ratio: 0.1
      std: 0.02
  relative_measurement: true
  #grid_path: /dccstor/gridfm/hector/data/perturbations-3/case14_ieee/perturbation_0.0_0/case14_ieee/processed/data_index_0.pt
data:
  baseMVA: 100
  mask_value: 0.0
  normalization: HeteroDataMVANormalizer
  networks:
  - case118_ieee
  scenarios:
  - 100000
  split_by_load_scenario_idx: true
  test_ratio: 0.1
  val_ratio: 0.1
  workers: 32
model:
  attention_head: 8
  edge_dim: 10
  hidden_size: 48
  input_bus_dim: 15
  input_gen_dim: 6
  output_bus_dim: 2
  output_gen_dim: 1
  num_layers: 12
  type: GNS_heterogeneous
optimizer:
  beta1: 0.9
  beta2: 0.999
  learning_rate: 0.0005
  lr_decay: 0.7
  lr_patience: 5
seed: 0
training:
  batch_size: 32
  epochs: 200
  losses:
  - LossPerDim
  - LossPerDim
  - LossPerDim
  - LossPerDim
  loss_weights:
  - 0.35
  - 0.35
  - 0.1
  - 0.1
  loss_args:
  - dim: VM
    loss_str: MAE
  - dim: VA
    loss_str: MAE
  - dim: P_in
    loss_str: MAE
  - dim: Q_in
    loss_str: MAE
  accelerator: auto
  devices: auto
  strategy: auto
verbose: true
